name: CI

on:
  pull_request:
    branches:
      - ["main"]

  worflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '12'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Deploy & Test Models (CI)
        run: dbt build --profiles-dir . --target ci

      